// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Web_API.Models;

#nullable disable

namespace Web_API.Migrations
{
    [DbContext(typeof(WebAPIDbContext))]
    partial class WebAPIDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InterestUser", b =>
                {
                    b.Property<int>("InterestsId")
                        .HasColumnType("int");

                    b.Property<int>("UsersId")
                        .HasColumnType("int");

                    b.HasKey("InterestsId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("InterestUser");

                    b.HasData(
                        new
                        {
                            InterestsId = 1,
                            UsersId = 1
                        },
                        new
                        {
                            InterestsId = 5,
                            UsersId = 1
                        },
                        new
                        {
                            InterestsId = 2,
                            UsersId = 2
                        },
                        new
                        {
                            InterestsId = 4,
                            UsersId = 2
                        },
                        new
                        {
                            InterestsId = 3,
                            UsersId = 3
                        },
                        new
                        {
                            InterestsId = 1,
                            UsersId = 3
                        },
                        new
                        {
                            InterestsId = 5,
                            UsersId = 4
                        },
                        new
                        {
                            InterestsId = 2,
                            UsersId = 4
                        },
                        new
                        {
                            InterestsId = 4,
                            UsersId = 5
                        },
                        new
                        {
                            InterestsId = 3,
                            UsersId = 5
                        });
                });

            modelBuilder.Entity("Web_API.Models.Interest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Interests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Capturing moments through a camera lens, from landscape to portrait photography.",
                            Name = "Photography"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Exploring nature trails and mountains on foot, enjoying the outdoors.",
                            Name = "Hiking"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Playing and discussing digital games across all genres, from indie to AAA.",
                            Name = "Video Games"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Experimenting with recipes and cuisines from around the world.",
                            Name = "Cooking"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Studying and applying ML algorithms and neural networks to real-world problems.",
                            Name = "Machine Learning"
                        });
                });

            modelBuilder.Entity("Web_API.Models.Link", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("InterestId")
                        .HasColumnType("int");

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InterestId");

                    b.HasIndex("UserId");

                    b.ToTable("Links");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InterestId = 1,
                            URL = "https://www.flickr.com/people/alicejohnson",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            InterestId = 5,
                            URL = "https://github.com/alicejohnson-ml",
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            InterestId = 2,
                            URL = "https://www.alltrails.com/members/bobmartinez",
                            UserId = 2
                        },
                        new
                        {
                            Id = 4,
                            InterestId = 4,
                            URL = "https://www.youtube.com/@bobcooks",
                            UserId = 2
                        },
                        new
                        {
                            Id = 5,
                            InterestId = 3,
                            URL = "https://store.steampowered.com/profiles/claranguyen",
                            UserId = 3
                        },
                        new
                        {
                            Id = 6,
                            InterestId = 1,
                            URL = "https://www.instagram.com/clara.shoots",
                            UserId = 3
                        },
                        new
                        {
                            Id = 7,
                            InterestId = 5,
                            URL = "https://www.kaggle.com/davidokonkwo",
                            UserId = 4
                        },
                        new
                        {
                            Id = 8,
                            InterestId = 2,
                            URL = "https://www.strava.com/athletes/davidokonkwo",
                            UserId = 4
                        },
                        new
                        {
                            Id = 9,
                            InterestId = 4,
                            URL = "https://www.foodnetwork.com/profiles/evalindstrom",
                            UserId = 5
                        },
                        new
                        {
                            Id = 10,
                            InterestId = 3,
                            URL = "https://www.twitch.tv/eva_plays",
                            UserId = 5
                        });
                });

            modelBuilder.Entity("Web_API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Alice Johnson",
                            Phone = "+1-555-0101"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Bob Martinez",
                            Phone = "+1-555-0202"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Clara Nguyen",
                            Phone = "+44-7700-900303"
                        },
                        new
                        {
                            Id = 4,
                            Name = "David Okonkwo",
                            Phone = "+46-70-440-0404"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Eva Lindström",
                            Phone = "+46-73-550-0505"
                        });
                });

            modelBuilder.Entity("InterestUser", b =>
                {
                    b.HasOne("Web_API.Models.Interest", null)
                        .WithMany()
                        .HasForeignKey("InterestsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Web_API.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Web_API.Models.Link", b =>
                {
                    b.HasOne("Web_API.Models.Interest", "Interest")
                        .WithMany("Links")
                        .HasForeignKey("InterestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Web_API.Models.User", "User")
                        .WithMany("Links")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Interest");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Web_API.Models.Interest", b =>
                {
                    b.Navigation("Links");
                });

            modelBuilder.Entity("Web_API.Models.User", b =>
                {
                    b.Navigation("Links");
                });
#pragma warning restore 612, 618
        }
    }
}
